spring:
  application:
    name: ms-sboot-auth
  mvc:
    problemdetails:
      enabled: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: ${SERVER_PORT:8081}

jwt:
  expiracao-minutos: ${JWT_EXPIRACAO_MINUTOS:15}
  refresh-expiracao-dias: ${JWT_REFRESH_DIAS:7}

app:
  url: ${APP_URL:http://localhost:3001}
